<?php

use PHPUnit\Framework\TestCase;
use Kubinyete\Edi\Getnet\Registry\Header;

class RegistryUnitTest extends TestCase
{
    public function testCanParseHeader()
    {
        $this->assertInstanceOf(Header::class, $e = Header::from(<<<EDI
        01403202417235913032024CEADM10000000000000000144992774000111MY ACQUIRER         000000001AASant. v.10.1 400 bytes   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        EDI));

        $this->assertEquals(0, $e->registryType);
    }
}
